# Generated by Django 4.2.3 on 2023-07-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_icon_icon_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='image',
            new_name='icon',
        ),
    ]
